name: torch-model
channels:
  - conda-forge
dependencies:
  - prefect
  - docker-py>=5.0
  - tensorflow
  - keras
  - pydantic
  - botorch>=0.8.2
  - ipywidgets
  - tqdm
  - matplotlib
  - jupyterlab
  - ipykernel
  - jupyter
  - nb_conda_kernels
  - pandas
  - pip
  - python=3.9
  - xopt
  - pip:
    - git+https://github.com/slaclab/lume-model.git
    - git+https://github.com/jbellister-slac/lume-services.git@prefect_2
